[package]
name = "psort"
version = "0.2.2"
authors = ["Sebastian Kriems <bastoberto@gmx.de>"]
description = "A small utility for sorting jpeg files by date"
license = "MIT"

[dependencies]
clap = "2.32.0"
chrono = "0.4.6"
kamadak-exif = "0.3.1"
