[package]
name = "psort"
version = "0.2.2"
authors = ["Sebastian Kriems <bastoberto@gmx.de>"]
description = "A small utility for sorting jpeg files by date"
license = "MIT"
edition = "2018"

[dependencies]
structopt = "0.2"
chrono = "0.4.6"
kamadak-exif = "0.3.1"
